[package]
name = "hydrodynamics-numerical"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2"
tokio = { version = "1.49.0", features=["full"] }
serde = { version = "1.0.228", features=["derive"] }
serde_json = "1"
toml = "0.9.12"
tokio-tungstenite = "0.28"
futures-util = "0.3"
